name: tractian_companies_assets
description: "A new Flutter project."


publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  result_dart: ^1.1.1
  equatable: ^2.0.5
  flutter_native_splash: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    - family:  CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"


flutter_native_splash:
  color: "#17192D"
  image: assets/images/tractian_logo.png

  android_12:
    color: "#17192D"
    image: assets/images/android_12_splash_icon.png
